### ISSUE TITLE
Exceptions when agents are shutting down

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#115]
When openshift controller is working, it logs a lot of exceptions indicating network problems (see attached log). Otherwise no problem observed, it creates an output and it seems fine, just a lot of exceptions in the log.

In this scenario controller had 3 agents.

[controller_working_but_exceptions.log](https://github.com/Hyperfoil/Hyperfoil/files/5033728/controller_working_but_exceptions.log)

**Comment by rvansa** [comment]
Yes, I haven't figured out an easy way to disable these yet/perform cleaner shutdown. I'll take a look later on; this is low-priority.

And btw. it's not related to Openshift at all. It's Hyperfoil Controller - for a bit I was confused that you're talking about the openshift operator.

**Comment by rvansa** [comment]
I've added a delay that should prevent these error messages on controller (there are still some messages logged on agent but that is not as visible).
