### ISSUE TITLE
Failure with few users in scenario.

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#116]
Running a scenario with openshift controller fails if number of users in any phase is lower than number of agents. 
In this case controller does not report any error. It will only log some exceptions and a message that it cannot found stats file. Also trying to download stats file results in Http Error 504.
See attached log. It contains exceptions noted in #115 but also contains some NullPointerExceptions.
[controller_NPE.log](https://github.com/Hyperfoil/Hyperfoil/files/5033757/controller_NPE.log)

**Comment by rvansa** [comment]
I've added a test running single user in 2eb7ed3084a5b019bf14eecdaa0e7b14a3647c6f

However I can't reproduce this anymore; I don't remember if I've already fixed that earlier (couldn't find any reference in git log, though). Please reopen if the issue persists.
