### ISSUE TITLE
randomUUID step

### ISSUE THREAD

**Issue by sparty02** [Hyperfoil/Hyperfoil#120]
Is there a way to generate UUIDs in test scenarios?

**Comment by sparty02** [comment]
Addressed via convo in zulip [here](https://hyperfoil.zulipchat.com/#narrow/stream/181362-general/topic/Random.20data/near/212829432)

**Comment by rvansa** [comment]
Let's keep the issue open until it gets implemented.

**Comment by rvansa** [comment]
Hi @sparty02 have you progressed with the implementation, or have you experienced any problems?

**Comment by rvansa** [comment]
@sparty02 Ping?

**Comment by rvansa** [comment]
Looks like this has been abandoned, I won't close the issue though because it's a nice first issue for new contributors.

**Comment by diegolovison** [comment]
Hi, I think https://github.com/Hyperfoil/Hyperfoil/pull/157 address this

**Comment by rvansa** [comment]
Implemented in #157
