### ISSUE TITLE
Errors when trying to deploy agent to AWS EC2 instance from local hyperfoil controller.

### ISSUE THREAD

**Issue by tonyxrmdavidson** [Hyperfoil/Hyperfoil#125]
When trying to deploy an agent to an AWS EC2 instance using the following yaml.  The yaml is based upon two-agents example in 'the getting started guide'. SSH is set up correctly and I can scp files to the instance without issues.

---
name: two-agents
agents:
  agent-one:
    user: ec2-user
    host: ec2-54-145-83-94.compute-1.amazonaws.com
    port: 22
http:
  host: http://hyperfoil.io
usersPerSec: 10
duration: 10s
scenario:
- test:
  - httpRequest:
      GET: /
---

The output from the run two agents. 

bin/cli.sh terminal
---
Agents: agent-one[STARTING]
Terminated: 2020/10/20 10:37:04.119
NAME  STATUS  STARTED  REMAINING  COMPLETED  TOTAL DURATION  DESCRIPTION
Errors:
Deployment timed out.
[hyperfoil@localhost]$ 
---

bin/controller.sh terminal
---
10:36:14,458 INFO  (main) [i.h.H.Controller] Java: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_191 25.191-b12 (/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre)
10:36:14,463 INFO  (main) [i.h.H.Controller] Hyperfoil: 0.9 (4269ea5c69ff96a8b35441d5718bc4f2d968da0f)
10:36:14,463 INFO  (main) [i.h.H.Controller]            DISTRIBUTION:  /Users/tonydavidson/hyperfoil-0.9
10:36:14,471 INFO  (main) [i.h.H.Controller]            ROOT_DIR:      /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil
10:36:14,471 INFO  (main) [i.h.H.Controller]            BENCHMARK_DIR: /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark
10:36:14,472 INFO  (main) [i.h.H.Controller]            RUN_DIR:       /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/run
10:36:14,472 INFO  (main) [i.h.H.Controller]            HOOKS_DIR:     /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/hooks
10:36:14,472 INFO  (main) [i.h.H.Controller] Starting Vert.x...
10:36:14,484 INFO  (main) [i.h.H.Controller] Using host name tdavidso-mac/192.168.0.6
10:36:15,056 INFO  (main) [i.h.HyperfoilChannelLookup] Reducing join timeout.
10:36:15,056 INFO  (main) [i.h.HyperfoilChannelLookup] Using 192.168.0.6:7800 as clustering address
10:36:15,071 INFO  (main) [o.j.p.p.GMS] tdavidso-mac-9462: no members discovered after 2 ms: creating cluster as first member
10:36:15,857 INFO  (vert.x-eventloop-thread-0) [i.h.H.Controller] Deploying ControllerVerticle...
10:36:15,863 INFO  (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Starting in directory /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil...
10:36:16,052 INFO  (vert.x-eventloop-thread-1) [o.a.s.c.u.s.e.EdDSASecurityProviderRegistrar] getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
10:36:16,115 INFO  (vert.x-eventloop-thread-1) [o.a.s.c.i.DefaultIoServiceFactoryFactory] No detected/configured IoServiceFactoryFactory using Nio2ServiceFactoryFactory
10:36:16,282 INFO  (vert.x-worker-thread-6) [i.h.c.u.PersistenceUtil] Loaded benchmark 'two-agents' from /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/two-agents.yaml
10:36:16,302 INFO  (vert.x-worker-thread-6) [i.h.c.u.PersistenceUtil] Loaded benchmark 'two-agents' from /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/two-agents.serialized
10:36:16,302 INFO  (vert.x-eventloop-thread-0) [i.h.H.Controller] ControllerVerticle deployed.
10:36:40,907 INFO  (vert.x-worker-thread-7) [i.h.c.u.PersistenceUtil] Stored benchmark 'two-agents' in /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/two-agents.serialized
10:36:40,909 INFO  (vert.x-worker-thread-7) [i.h.c.u.PersistenceUtil] Stored benchmark 'two-agents' in /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/two-agents.yaml
10:36:49,115 INFO  (vert.x-eventloop-thread-1) [i.h.c.u.PersistenceUtil] Stored benchmark 'two-agents' in /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/run/001C/two-agents.serialized
10:36:49,116 INFO  (vert.x-eventloop-thread-1) [i.h.c.u.PersistenceUtil] Stored benchmark 'two-agents' in /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/run/001C/two-agents.yaml
10:36:49,116 INFO  (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Starting agents for run 001C
10:36:49,128 INFO  (vert.x-worker-thread-8) [o.a.s.c.c.h.DefaultConfigFileHostEntryResolver] resolveEffectiveResolver(ec2-user@ec2-54-145-83-94.compute-1.amazonaws.com:22) loaded 3 entries from /Users/tonydavidson/.ssh/config
10:36:52,188 WARN  (vert.x-worker-thread-8) [o.a.s.c.s.ScpHelper] readAck(ScpHelper[ClientSessionImpl[ec2-user@ec2-54-145-83-94.compute-1.amazonaws.com/54.145.83.94:22]])[EOF=false] - Received warning: scp: /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/agentlib/vertx-web-3.8.3.jar: No such file or directory
10:36:52,483 WARN  (vert.x-worker-thread-8) [o.a.s.c.s.ScpHelper] readAck(ScpHelper[ClientSessionImpl[ec2-user@ec2-54-145-83-94.compute-1.amazonaws.com/54.145.83.94:22]])[EOF=false] - Received warning: scp: protocol error: expected control record
10:36:52,484 WARN  (vert.x-worker-thread-8) [o.a.s.c.s.DefaultScpClient] handleCommandExitStatus(ClientSessionImpl[ec2-user@ec2-54-145-83-94.compute-1.amazonaws.com/54.145.83.94:22]) cmd='scp -p -t -- /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/agentlib/vertx-web-3.8.3.jar' may have terminated with some problems
...
...
10:37:20,450 WARN  (vert.x-worker-thread-8) [o.a.s.c.s.ScpHelper] readAck(ScpHelper[ClientSessionImpl[ec2-user@ec2-54-145-83-94.compute-1.amazonaws.com/54.145.83.94:22]])[EOF=false] - Received warning: scp: /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/agentlib/vertx-core-3.8.3.jar: No such file or directory
10:37:20,551 WARN  (vert.x-worker-thread-8) [o.a.s.c.s.ScpHelper] readAck(ScpHelper[ClientSessionImpl[ec2-user@ec2-54-145-83-94.compute-1.amazonaws.com/54.145.83.94:22]])[EOF=false] - Received warning: scp: protocol error: expected control record
10:37:20,551 WARN  (vert.x-worker-thread-8) [o.a.s.c.s.DefaultScpClient] handleCommandExitStatus(ClientSessionImpl[ec2-user@ec2-54-145-83-94.compute-1.amazonaws.com/54.145.83.94:22]) cmd='scp -p -t -- /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/agentlib/vertx-core-3.8.3.jar' may have terminated with some problems
10:37:45,810 WARN  (vert.x-worker-thread-8) [o.a.s.c.s.ScpHelper] readAck(ScpHelper[ClientSessionImpl[ec2-user@ec2-54-145-83-94.compute-1.amazonaws.com/54.145.83.94:22]])[EOF=false] - Received warning: scp: /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/agentlib/infinispan-core-9.4.10.Final.jar: No such file or directory
10:37:46,213 ERROR (vert.x-worker-thread-8) [i.h.c.ControllerVerticle] Failed to deploy agent agent-one org.apache.sshd.common.channel.WindowClosedException: Already closed: Window[client/remote](ChannelExec[id=49, recipient=2]-ClientSessionImpl[ec2-user@ec2-54-145-83-94.compute-1.amazonaws.com/54.145.83.94:22])
	at org.apache.sshd.common.channel.Window.waitForCondition(Window.java:302)
	at org.apache.sshd.common.channel.Window.waitForSpace(Window.java:252)
	at org.apache.sshd.common.channel.ChannelOutputStream.flush(ChannelOutputStream.java:188)
	at org.apache.sshd.common.channel.ChannelOutputStream.write(ChannelOutputStream.java:127)
	at org.apache.sshd.common.util.io.IoUtils.copy(IoUtils.java:129)
	at org.apache.sshd.common.scp.ScpHelper.sendStream(ScpHelper.java:561)
	at org.apache.sshd.common.scp.ScpHelper.sendFile(ScpHelper.java:491)
	at org.apache.sshd.common.scp.ScpHelper.send(ScpHelper.java:449)
	at org.apache.sshd.common.scp.ScpHelper.send(ScpHelper.java:426)
	at org.apache.sshd.client.scp.AbstractScpClient.lambda$upload$0(AbstractScpClient.java:153)
	at org.apache.sshd.client.scp.DefaultScpClient.runUpload(DefaultScpClient.java:144)
	at org.apache.sshd.client.scp.AbstractScpClient.upload(AbstractScpClient.java:152)
	at org.apache.sshd.client.scp.ScpClient.upload(ScpClient.java:108)
	at org.apache.sshd.client.scp.ScpClient.upload(ScpClient.java:104)
	at io.hyperfoil.deploy.ssh.SshDeployedAgent.deploy(SshDeployedAgent.java:134)
	at io.hyperfoil.deploy.ssh.SshDeployer.start(SshDeployer.java:92)
	at io.hyperfoil.clustering.ControllerVerticle.lambda$startBenchmark$17(ControllerVerticle.java:443)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

10:37:46,215 WARN  (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Run 001C already completed.
---

**Comment by rvansa** [comment]
@tonyxrmdavidson Thanks for the report. Hyperfoil is copying its JARs to target machine. I guess that the message
```
scp: /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/agentlib/vertx-web-3.8.3.jar: No such file or directory
```
means that some of the parent directories have not been created when calling `mkdir -p something/agentlib` - likely a permission issue. The `/var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T` part comes from `java.io.tmpdir` system property on the controller machine - it makes sense that in your case it's not the same on the agent.

Please add `dir` property to your agent:
```yaml
name: two-agents
agents:
  agent-one:
    user: ec2-user
    host: ec2-54-145-83-94.compute-1.amazonaws.com
    dir: /path/to/some/writable/directory    
http:
  host: http://hyperfoil.io
usersPerSec: 10
duration: 10s
scenario:
- test:
  - httpRequest:
      GET: /
```

**Comment by tonyxrmdavidson** [comment]
Thanks rvasnsa,  I appreciate your quick response.

**Comment by tonyxrmdavidson** [comment]
Hi rvansa,

What dependencies need to be installed in the host machine agents are deployed to?
 
Thanks

tonyxrmdavidson

**Comment by rvansa** [comment]
@tonyxrmdavidson There should be `java` and `openssl` if you want to run over HTTPS.

**Comment by tonyxrmdavidson** [comment]
Thanks rvansa

**Comment by tonyxrmdavidson** [comment]
When I run locally I can now get the agent to deploy to my EC2 instance. However I am running into issues with vertex-x thread-blocking.  Is this something that has been seen before?

**In controller**

> 09:47:34,653 INFO  (main) [i.h.H.Controller] Java: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_191 25.191-b12 (/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre)
> 09:47:34,659 INFO  (main) [i.h.H.Controller] Hyperfoil: 0.9 (4269ea5c69ff96a8b35441d5718bc4f2d968da0f)
> 09:47:34,659 INFO  (main) [i.h.H.Controller]            DISTRIBUTION:  /Users/tonydavidson/hyperfoil-0.9
> 09:47:34,670 INFO  (main) [i.h.H.Controller]            ROOT_DIR:      /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil
> 09:47:34,671 INFO  (main) [i.h.H.Controller]            BENCHMARK_DIR: /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark
> 09:47:34,671 INFO  (main) [i.h.H.Controller]            RUN_DIR:       /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/run
> 09:47:34,671 INFO  (main) [i.h.H.Controller]            HOOKS_DIR:     /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/hooks
> 09:47:34,672 INFO  (main) [i.h.H.Controller] Starting Vert.x...
> 09:47:34,690 INFO  (main) [i.h.H.Controller] Using host name tdavidso-mac/192.168.0.6
> 09:47:35,632 INFO  (main) [i.h.HyperfoilChannelLookup] Reducing join timeout.
> 09:47:35,632 INFO  (main) [i.h.HyperfoilChannelLookup] Using 192.168.0.6:7800 as clustering address
> 09:47:35,654 INFO  (main) [o.j.p.p.GMS] tdavidso-mac-34400: no members discovered after 3 ms: creating cluster as first member
> 09:47:36,595 INFO  (vert.x-eventloop-thread-0) [i.h.H.Controller] Deploying ControllerVerticle...
> 09:47:36,602 INFO  (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Starting in directory /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil...
> 09:47:36,868 INFO  (vert.x-eventloop-thread-1) [o.a.s.c.u.s.e.EdDSASecurityProviderRegistrar] getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
> 09:47:36,951 INFO  (vert.x-eventloop-thread-1) [o.a.s.c.i.DefaultIoServiceFactoryFactory] No detected/configured IoServiceFactoryFactory using Nio2ServiceFactoryFactory
> 09:47:37,158 INFO  (vert.x-worker-thread-6) [i.h.c.u.PersistenceUtil] Loaded benchmark 'two-agents' from /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/two-agents.yaml
> 09:47:37,181 INFO  (vert.x-worker-thread-6) [i.h.c.u.PersistenceUtil] Loaded benchmark 'two-agents' from /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/two-agents.serialized
> 09:47:37,186 INFO  (vert.x-worker-thread-6) [i.h.c.u.PersistenceUtil] Loaded benchmark 'single-request' from /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/single-request.yaml
> 09:47:37,190 INFO  (vert.x-worker-thread-6) [i.h.c.u.PersistenceUtil] Loaded benchmark 'single-request' from /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/single-request.serialized
> 09:47:37,191 INFO  (vert.x-eventloop-thread-0) [i.h.H.Controller] ControllerVerticle deployed.
> 09:47:58,121 INFO  (vert.x-worker-thread-7) [i.h.c.u.PersistenceUtil] Stored benchmark 'two-agents' in /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/two-agents.serialized
> 09:47:58,122 INFO  (vert.x-worker-thread-7) [i.h.c.u.PersistenceUtil] Stored benchmark 'two-agents' in /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/benchmark/two-agents.yaml
> 09:48:01,505 INFO  (vert.x-eventloop-thread-1) [i.h.c.u.PersistenceUtil] Stored benchmark 'two-agents' in /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/run/0025/two-agents.serialized
> 09:48:01,505 INFO  (vert.x-eventloop-thread-1) [i.h.c.u.PersistenceUtil] Stored benchmark 'two-agents' in /var/folders/f7/n623zvcj7tndvtmht5kkm0tw0000gn/T/hyperfoil/run/0025/two-agents.yaml
> 09:48:01,506 INFO  (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Starting agents for run 0025
> 09:48:01,517 INFO  (vert.x-worker-thread-8) [o.a.s.c.c.h.DefaultConfigFileHostEntryResolver] resolveEffectiveResolver(ec2-user@ec2-52-207-21-88.compute-1.amazonaws.com:22) loaded 3 entries from /Users/tonydavidson/.ssh/config
> 09:48:16,508 ERROR (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] 0025 Deployment timed out.
> 09:49:02,272 WARN  (vertx-blocked-thread-checker) [i.v.c.i.BlockedThreadChecker] Thread Thread[vert.x-worker-thread-8,5,main]=Thread[vert.x-worker-thread-8,5,main] has been blocked for 60763 ms, time limit is 60000 ms io.vertx.core.VertxException: Thread blocked
> 	at sun.misc.Unsafe.park(Native Method)
> 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
> 	at org.apache.sshd.common.channel.ChannelPipedInputStream.read(ChannelPipedInputStream.java:139)
> 	at org.apache.sshd.common.channel.ChannelPipedInputStream.read(ChannelPipedInputStream.java:100)
> 	at org.apache.sshd.common.scp.ScpHelper.readAck(ScpHelper.java:809)
> 	at org.apache.sshd.common.scp.ScpHelper.sendStream(ScpHelper.java:531)
> 	at org.apache.sshd.common.scp.ScpHelper.sendFile(ScpHelper.java:491)
> 	at org.apache.sshd.common.scp.ScpHelper.send(ScpHelper.java:449)
> 	at org.apache.sshd.common.scp.ScpHelper.send(ScpHelper.java:426)
> 	at org.apache.sshd.client.scp.AbstractScpClient.lambda$upload$0(AbstractScpClient.java:153)
> 	at org.apache.sshd.client.scp.AbstractScpClient$$Lambda$662/2101457864.execute(Unknown Source)
> 	at org.apache.sshd.client.scp.DefaultScpClient.runUpload(DefaultScpClient.java:144)
> 	at org.apache.sshd.client.scp.AbstractScpClient.upload(AbstractScpClient.java:152)
> 	at org.apache.sshd.client.scp.ScpClient.upload(ScpClient.java:108)
> 	at org.apache.sshd.client.scp.ScpClient.upload(ScpClient.java:104)
> 	at io.hyperfoil.deploy.ssh.SshDeployedAgent.deploy(SshDeployedAgent.java:134)
> 	at io.hyperfoil.deploy.ssh.SshDeployer.start(SshDeployer.java:92)
> 	at io.hyperfoil.clustering.ControllerVerticle.lambda$startBenchmark$17(ControllerVerticle.java:443)
> 	at io.hyperfoil.clustering.ControllerVerticle$$Lambda$608/169016428.handle(Unknown Source)
> 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
> 	at io.vertx.core.impl.ContextImpl$$Lambda$266/892237946.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> ...
> ...
> 
> 09:49:34,349 WARN  (vertx-blocked-thread-checker) [i.v.c.i.BlockedThreadChecker] Thread Thread[vert.x-worker-thread-8,5,main]=Thread[vert.x-worker-thread-8,5,main] has been blocked for 92839 ms, time limit is 60000 ms io.vertx.core.VertxException: Thread blocked
> 	at sun.misc.Unsafe.park(Native Method)
> 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
> 	at org.apache.sshd.common.channel.ChannelPipedInputStream.read(ChannelPipedInputStream.java:139)
> 	at org.apache.sshd.common.channel.ChannelPipedInputStream.read(ChannelPipedInputStream.java:100)
> 	at org.apache.sshd.common.scp.ScpHelper.readAck(ScpHelper.java:809)
> 	at org.apache.sshd.common.scp.ScpHelper.sendStream(ScpHelper.java:570)
> 	at org.apache.sshd.common.scp.ScpHelper.sendFile(ScpHelper.java:491)
> 	at org.apache.sshd.common.scp.ScpHelper.send(ScpHelper.java:449)
> 	at org.apache.sshd.common.scp.ScpHelper.send(ScpHelper.java:426)
> 	at org.apache.sshd.client.scp.AbstractScpClient.lambda$upload$0(AbstractScpClient.java:153)
> 	at org.apache.sshd.client.scp.AbstractScpClient$$Lambda$662/2101457864.execute(Unknown Source)
> 	at org.apache.sshd.client.scp.DefaultScpClient.runUpload(DefaultScpClient.java:144)
> 	at org.apache.sshd.client.scp.AbstractScpClient.upload(AbstractScpClient.java:152)
> 	at org.apache.sshd.client.scp.ScpClient.upload(ScpClient.java:108)
> 	at org.apache.sshd.client.scp.ScpClient.upload(ScpClient.java:104)
> 	at io.hyperfoil.deploy.ssh.SshDeployedAgent.deploy(SshDeployedAgent.java:134)
> 	at io.hyperfoil.deploy.ssh.SshDeployer.start(SshDeployer.java:92)
> 	at io.hyperfoil.clustering.ControllerVerticle.lambda$startBenchmark$17(ControllerVerticle.java:443)
> 	at io.hyperfoil.clustering.ControllerVerticle$$Lambda$608/169016428.handle(Unknown Source)
> 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
> 	at io.vertx.core.impl.ContextImpl$$Lambda$266/892237946.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:748)

**In agent.agent-one.log in EC2 instance**

> [ec2-user@ip-10-11-128-6 hyperfoil]$ cat agent.agent-one.log 
> 08:49:36,132 INFO  (main) [i.h.H.Controller] Java: Oracle Corporation OpenJDK 64-Bit Server VM 1.8.0_265 25.265-b01 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.265.b01-0.el8_2.x86_64/jre)
> 08:49:36,136 INFO  (main) [i.h.H.Controller] Hyperfoil: 0.9 (4269ea5c69ff96a8b35441d5718bc4f2d968da0f)
> 08:49:36,136 INFO  (main) [i.h.H.Controller]            DISTRIBUTION:  /home/ec2-user/hyperfoil
> 08:49:36,149 INFO  (main) [i.h.H.Controller]            ROOT_DIR:      /tmp/hyperfoil
> 08:49:36,150 INFO  (main) [i.h.H.Controller]            BENCHMARK_DIR: /tmp/hyperfoil/benchmark
> 08:49:36,150 INFO  (main) [i.h.H.Controller]            RUN_DIR:       /tmp/hyperfoil/run
> 08:49:36,150 INFO  (main) [i.h.H.Controller]            HOOKS_DIR:     /tmp/hyperfoil/hooks
> 08:49:36,151 INFO  (main) [i.h.H.Controller] Starting Vert.x...
> 08:49:36,173 INFO  (main) [i.h.H.Controller] Using host name ip-10-11-128-6.ec2.internal/10.11.128.6
> 08:49:37,501 INFO  (main) [i.h.HyperfoilChannelLookup] Connecting to controller 192.168.0.6:7800
> 08:49:37,502 INFO  (main) [i.h.HyperfoilChannelLookup] Using 10.11.128.6:7800 as clustering address
> 08:49:42,847 INFO  (main) [o.j.p.p.GMS] ip-10-11-128-6-3539: no members discovered after 5308 ms: creating cluster as first member
> 08:49:45,488 INFO  (vert.x-eventloop-thread-0) [i.h.H.Controller] Deploying AgentVerticle...
> 08:49:45,505 INFO  (vert.x-eventloop-thread-0) [i.h.H.Controller] AgentVerticle deployed.
> 08:49:46,517 INFO  (vert.x-eventloop-thread-1) [i.h.c.AgentVerticle] a26025fa-c14b-4a0d-a62d-0aa4580d0997 Failed to register: NO_HANDLERS
> 08:49:47,506 INFO  (vert.x-eventloop-thread-1) [i.h.c.AgentVerticle] a26025fa-c14b-4a0d-a62d-0aa4580d0997 Failed to register: NO_HANDLERS
> 08:49:48,506 INFO  (vert.x-eventloop-thread-1) [i.h.c.AgentVerticle] a26025fa-c14b-4a0d-a62d-0aa4580d0997 Failed to register: NO_HANDLERS
> 08:49:49,507 INFO  (vert.x-eventloop-thread-1) [i.h.c.AgentVerticle] a26025fa-c14b-4a0d-a62d-0aa4580d0997 Failed to register: NO_HANDLERS
> ...
> ...
> 08:50:48,506 INFO  (vert.x-eventloop-thread-1) [i.h.c.AgentVerticle] a26025fa-c14b-4a0d-a62d-0aa4580d0997 Failed to register: NO_HANDLERS
> 08:50:49,506 INFO  (vert.x-eventloop-thread-1) [i.h.c.AgentVerticle] a26025fa-c14b-4a0d-a62d-0aa4580d0997 Failed to register: NO_HANDLERS
> 08:50:50,506 INFO  (vert.x-eventloop-thread-1) [i.h.c.AgentVerticle] a26025fa-c14b-4a0d-a62d-0aa4580d0997 Failed to register: NO_HANDLERS
> 08:50:51,506 INFO  (vert.x-eventloop-thread-1) [i.h.c.AgentVerticle] a26025fa-c14b-4a0d-a62d-0aa4580d0997 Failed to register: NO_HANDLERS
> [ec2-user@ip-10-11-128-6 hyperfoil]$

**Comment by rvansa** [comment]
@tonyxrmdavidson It seems that it's taking very long to copy the files to the agent nodes; default timeout could be too short for your env. It took more than 90 seconds to copy & start the agent and some part of the process was already cancelled.
Although subsequent runs should be faster (if the path on agent doesn't change) I suggest increasing the timeout to, say 3 minutes to be on the safe side: add `-Dio.hyperfoil.deploy.timeout=180000` to the `controller.sh`.  

However I am a bit worried about
```
08:49:42,847 INFO  (main) [o.j.p.p.GMS] ip-10-11-128-6-3539: no members discovered after 5308 ms: creating cluster as first member
```
It seems that agent binds to `10.11.128.6:7800` (Hyperfoil selects this address using reverse hostname lookup) and tries to connect to `192.168.0.6:7800` which is obviously on a different network. So either put controller on the 10.x.y.z network using `-Dio.hyperfoil.controller.cluster.ip=10.123.45.68` (replace with its real IP ofc) or let agents bind to `192.168.x.y` using

```yaml
agents:
  agent-one:
    user: ec2-user
    host: ec2-54-145-83-94.compute-1.amazonaws.com
    dir: /path/to/some/writable/directory 
    extras: -Djgroups.tcp.address=192.168.x.y
```

**Comment by rvansa** [comment]
(And yes, clustering sucks. Anywhere. Sorry.)

**Comment by tonyxrmdavidson** [comment]
Thanks Radim.  I appreciate your quick response.

**Comment by tonyxrmdavidson** [comment]
Hi Radim,
When I increase the timeout, do I add it at the end of controller.sh or pass it as variable when I run the script?

**Comment by rvansa** [comment]
@tonyxrmdavidson IIRC you can just run it as `./controller.sh -Dio.hyperfoil.deploy.timeout=180000`, it's passing any options as arguments to `java`.

**Comment by rvansa** [comment]
As per other discussion, the major problem was in running controller & agents in different networks (controller port 7800 not reachable from agents).
