### ISSUE TITLE
RandomItem: File from URL

### ISSUE THREAD

**Issue by eloycoto** [Hyperfoil/Hyperfoil#137]
When running the testsuite, if you have a randomitem::file, you always need to upload that to the server from cli. If the file is big, the upload timeout is not enough. 

It will be cool to use a file from an HTTP server

```
          - randomItem:
              file: http://foo.com/large.txt
              toVar: body_payload
```

Regards

**Comment by rvansa** [comment]
With `0.12` you don't need to re-upload it; CLI asks when the benchmark is edited using `edit`. Also, you can now set system property `io.hyperfoil.cli.request.timeout` (in milliseconds) in CLI to adjust request timeout.

With text-mode uploads it could work, though it would further complicate the reasoning about where to fetch from - the file would have to be downloaded and persisted in controller anyway (agents would receive from controller). I am afraid that some users might get confused that this is not refreshed on every run (it's a bit more obvious that it won't be fetched from local disk).

What exactly is your usecase? If you're working through CLI I assume that you're doing that manually. You can just use `edit`. The benchmark is supposed to live on the controller, so you should not need to really upload it too often.

**Comment by eloycoto** [comment]
works for me! Thanks
