### ISSUE TITLE
Long variables

### ISSUE THREAD

**Issue by slinkydeveloper** [Hyperfoil/Hyperfoil#171]
I'm trying to implement a TimestampStep that uses `System.currentTimeMillis()` to get the timestamp and store it in a variable.

But there is no long support for variables, so I had to store it as String. Does it makes sense to have the support for primitive `long` variables?

**Comment by slinkydeveloper** [comment]
Context: https://github.com/slinkydeveloper/eventing-hyperfoil-benchmark/blob/main/timestamp-hyperfoil-extension/src/main/java/com/slinkydeveloper/hyperfoil/extensions/TimestampStep.java

**Comment by rvansa** [comment]
HF does not try to implement support for all the primitives; as you will be converting the timestamp to `CharSequence` for header it's fine if you store that as string anyway.

**Comment by slinkydeveloper** [comment]
@rvansa that's what I do in my impl, I was wondering: is it generic enough? Could there be some users that might profit from having it represented as long (e.g. for doing computations?)

Anyway, I'll PR it soon and we can continue this discussion there

**Comment by rvansa** [comment]
I believe it is. I don't expect any time-related calculations as part of the benchmark, and eventually this will be serialized into a buffer in a human readable form. Maybe in the future we'll need some formatting of the timestamp and that would end up as string, too.
I only wonder if the step should by just `timestamp` or more something like `setCurrentTimestamp`.
Closing this issue (I believe the discussion is resolved), I'll be awaiting the PR.
