### ISSUE TITLE
gap in timeseries data from vertx-receiver

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Hyperfoil#189]
The timeseries data for the vert-recever cloudevents has ~20s gaps between phases. It appears the data is missing from the start of a phase and is being combined with the T+20 data creating a spike in request / responses for that statistics window. We see this with a `staircase` workload but I suspect it would happen for any new phase. 
It isn't yet clear if it issue is in HF or how the vertx-receiver sends statistics to HF.

The vertx-recevier is found here: https://github.com/willr3/eventing-hyperfoil-benchmark/blob/main/vertx-receiver/src/main/java/com/slinkydeveloper/eventing/hyperfoil/benchmark/VertxReceiverVerticle.java

**Comment by rvansa** [comment]
There are actually two problems: what we see is that `VertxReceiverVerticle.recorded` is not set and therefore the statistics are automatically restarted every 60 seconds. And there's another issue as well: the receiver assumes in its simplicity that it will receive the from each phase monotonically - there won't be interleaving messages from two phases. If this happens it will restart counting statistics and we will start from sequence ID anew.

**Comment by rvansa** [comment]
I've fixed all the issues in https://github.com/rvansa/eventing-hyperfoil-benchmark
Note that this also delays stats completion - it requires HF `0.17-SNAPSHOT` version.
