### ISSUE TITLE
Odd results from asynchrous event testing

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Hyperfoil#205]
We load events into knative-eventing with Hyperfoil then have a receiver that sends the measured response time back to Hyperfiol.
https://github.com/openshift-knative/eventing-hyperfoil-benchmark/tree/main/vertx-receiver

The events are loading as expected:
![image](https://user-images.githubusercontent.com/1083859/139075395-4249a4fd-9876-4cb4-ae8a-8dc97b80fee2.png)

But the charts for the events from the receiver do not include events from the entire run
![image](https://user-images.githubusercontent.com/1083859/139075561-2ea3ed62-8b76-447a-a0d3-979071476d80.png)

The logs from the receiver frequently mention
* `Record start timestamp X predates statistics start X`
* `Response time X exceeded maximum trackable response time 60000000000`
* 
[receiver.log](https://github.com/Hyperfoil/Hyperfoil/files/7426493/receiver.log)

I turned on trace level logging in the controller with 
```
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
      <Appenders>
        <Console name="CONSOLE" target="SYSTEM_OUT">
          <PatternLayout pattern="%d{HH:mm:ss,SSS} %-5p [%c] (%t) %m%n"/>
        </Console>
      </Appenders>
      <Loggers>
        <Root level="TRACE">
          <AppenderRef ref="CONSOLE"/>
        </Root>
      </Loggers>
    </Configuration>
```
[controller.log](https://github.com/Hyperfoil/Hyperfoil/files/7426439/controller.log)

**Comment by willr3** [comment]
I think the new `${hyperfoil.phase.start.time.as.string}` is not yet recognized when uploading benchmarks.
```
upload /tmp/eventing-staircase.yaml
ERROR: No special variable hyperfoil.phase.start.time.as.string
Failed to parse the benchmark.
```

**Comment by rvansa** [comment]
You need to use CLI built from master; the benchmark is constructed for validation in CLI, too.

**Comment by rvansa** [comment]
Closing this as we have probably fixed it in the receiver.
