### ISSUE TITLE
No installation for pure k8s

### ISSUE THREAD

**Issue by sebgoa** [Hyperfoil/Hyperfoil#206]
hi,

Looking into the installation steps at https://hyperfoil.io/userguide/installation/k8s_manual.html there is no way to install this on a "pure" k8s cluster.

The documentation references the openshift operator and the `oc` CLI. Even the script used to pipe through oc makes us of the `Route` object: https://raw.githubusercontent.com/Hyperfoil/Hyperfoil/master/k8s-deployer/hyperfoil.yaml

It would be nice to have a script of yaml in the release that we could simply `kubectl apply`

**Comment by rvansa** [comment]
Yes, I would excuse myself that I don't have any vanilla K8s to test on (and no experience what to use instead of routes, without templates etc). If you could contribute something I can definitely include that (ideally if you also file a PR against docs on the website - https://github.com/Hyperfoil/hyperfoil.github.io ). Thanks!

**Comment by rvansa** [comment]
Hi @cfilleke, in Openshift this is distributed in `catalogsource` Community Operators: see https://docs.openshift.com/container-platform/4.10/operators/understanding/olm-rh-catalogs.html . When the operator is adjusted to work on vanilla K8s it will make sense to publish it on operatorhub.io.

I think the operator SDK creates only amd64 images by default. It seems that the SDK supports other architectures as well but likely it's not straightforward: https://sdk.operatorframework.io/docs/advanced-topics/multi-arch/

I am eager to accept any contributions that enable other users to try out Hyperfoil in their clusters! Looks like getting that work on Minishift would be a great first step.

**Comment by rvansa** [comment]
Hyperfoil operator has been published: https://operatorhub.io/operator/hyperfoil-bundle
