### ISSUE TITLE
Fix the statistics duration in the hyperfoil-maven-plugin / hyperfoil api

### ISSUE THREAD

**Issue by aldettinger** [Hyperfoil/Hyperfoil#210]
Using the hyperfoil-maven-plugin, no matter what a phase duration really is, the report duration is always 16s as below:
```
16:45:35,989 INFO  (main) [i.h.m.RunMojo] 60256 requests in 16.0s
```

This fails the computation of the reported throughput. For instance, in example above the duration was 60s, so the correct throughput to be reported should be `60256/60` and NOT `60256/16`.

I think the issue may lie in the [io.hyperfoil.api.statistics.Statistics class](https://github.com/Hyperfoil/Hyperfoil/blob/master/api/src/main/java/io/hyperfoil/api/statistics/Statistics.java). For instance, when `publish` is called, I've noticed that the size the of the `AtomicReferenceArray<StatisticsSnapshot> array` is always 16. While, I would expect the size to be 60 in my case, as we should have 60 samples of 1 second.

Interestingly, the default size of the [active and inactive samples array is 16](https://github.com/Hyperfoil/Hyperfoil/blob/master/api/src/main/java/io/hyperfoil/api/statistics/Statistics.java#L50..L51).
And if I change the hardcoded value to 60 that matches my current setup, then the hypefoil-maven-plugin output looks better.

Are those active and inactive sample arrays designed to be resized on the fly ? Does anybody has an idea to fix this correctly ?

**Comment by rvansa** [comment]
Hi @aldettinger , thanks for the report. I am convinced this runs correctly using the other ways to execute benchmark; I haven't run the RunMojo in a while. Will check it up.

**Comment by rvansa** [comment]
@aldettinger You were right, the stats did not work correctly. RunMojo and testsuite are the only places that use LocalSimulationRunner, a component that mocks/overrides the Vert.x controller-agents architecture. I've fixed this.

Btw. I wonder how you managed to run Hyperfoil using the Mojo - when I've tried to run it I saw complaints about missing dependency to testsuite. I've fixed that as well (hopefully it won't break the release).

**Comment by aldettinger** [comment]
@rvansa I've seen https://github.com/Hyperfoil/Hyperfoil/commit/962a255b60fbc5b824ac7df5ba7fad206b837696. I will try the SNAPSHOT when I have time.

I've managed to run the mojo by overriding the dependencies like below:
```
  <build>
    <plugins>
      <plugin>
        <groupId>io.hyperfoil</groupId>
        <artifactId>hyperfoil-maven-plugin</artifactId>
        <version>0.17</version>
        <configuration>
          <yaml>cq-perf-regression-scenario.hf.yaml</yaml>
          <percentiles>true</percentiles>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>io.hyperfoil</groupId>
            <artifactId>hyperfoil-test-suite</artifactId>
            <type>pom</type>
            <version>0.2</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
```
Good to know that it may be fixed. I will try it against the new SNAPSHOT and probably later on against the next release.

**Comment by aldettinger** [comment]
@rvansa Ok, I've double-checked the SNAPSHOT version locally and the reported statistics look far better :+1: 

I was also able to remove the hyperfoil-test-suite dependency override successfully against the local SNAPSHOT. I will have a try on next release. Many thanks for prompt reaction.
