### ISSUE TITLE
hyperfoil-maven-plugin: io.hyperfoil:hyperfoil-test-suite:pom:0.18 was not found

### ISSUE THREAD

**Issue by aldettinger** [Hyperfoil/Hyperfoil#219]
Hello,

  I've updated to hyperfoil-maven-plugin version 0.18. I face an issue where hyperfoil-test-suite:0.18 would [be needed](https://github.com/Hyperfoil/Hyperfoil/blob/master/plugins/maven/pom.xml#L23..#L31) but it's not published to maven central. When using the hyperfoil-maven-plugin, below issue is reported:
```
[INFO] --- hyperfoil-maven-plugin:0.18:run (default) @ cq-perf-regression-sample ---
[WARNING] The POM for io.hyperfoil:hyperfoil-test-suite:pom:0.18 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.778 s
[INFO] Finished at: 2022-02-17T14:14:42+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.hyperfoil:hyperfoil-maven-plugin:0.18:run (default) on project cq-perf-regression-sample: Execution default of goal io.hyperfoil:hyperfoil-maven-plugin:0.18:run failed: Plugin io.hyperfoil:hyperfoil-maven-plugin:0.18 or one of its dependencies could not be resolved: io.hyperfoil:hyperfoil-test-suite:pom:0.18 was not found in https://repository.apache.org/content/repositories/orgapachecamel-1379 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of camel-quarkus-staging has elapsed or updates are forced -> [Help 1]
```

  I can still use the workaround described [here](https://github.com/Hyperfoil/Hyperfoil/issues/210#issuecomment-990825054). But I wonder if there would be a cleaner solution ?

**Comment by rvansa** [comment]
Damned, so it stopped working again. Thanks for reporting - I remember I had another issue during release that made me to reorder things again the other way, but apparently it's not working. I'll have a look next week.

**Comment by rvansa** [comment]
Okay, now checking again I see that I've changed packaging of test-suite to `pom` before the release, and then after the release I reverted the change (because with pom packaging the test suite was not running) but installing the `pom` file to the local repository manually. TBH I don't know what happens during a release now; I'll try to deploy `0.19` this week after resolving some problems and will check if the maven plugin works as expected.

**Comment by rvansa** [comment]
Btw. another workaround would be installing the pom file directly into your repository:
```
mvn archetype:generate \
   -DarchetypeGroupId=org.apache.maven.archetypes -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 \
   -DgroupId=io.hyperfoil -DartifactId=hyperfoil-test-suite -Dversion=0.18 \
   -DinteractiveMode=false -DoutputDirectory=/tmp
mvn install:install-file \
   -Dfile=/tmp/hyperfoil-test-suite/pom.xml -DgroupId=io.hyperfoil -DartifactId=hyperfoil-test-suite -Dversion=0.18 -Dpackaging=pom
```

**Comment by aldettinger** [comment]
Out of curiosity. Is the test-suite really needed on the user's machine ?

I wonder whether it would be possible to scope the dependency as provided. Just an idea, that it would still reorder the maven reactor while not being explicitly needed on the user's machine.

**Comment by rvansa** [comment]
It's not needed (as the comment explains) - you're right, it seems that that would do the trick. I've removed the pom file from local repository and tried running 0-19-SNAPSHOT with `<scope>provided</scope>` and it worked.

**Comment by aldettinger** [comment]
Potentially, a good solution then. Let's see whether a full release could be performed with that. And I'll be happy to test from the user's machine perspective once 0.19 is released.

**Comment by rvansa** [comment]
Thanks for the confirmation!
