### ISSUE TITLE
Provide date format option for timestamp step

### ISSUE THREAD

**Issue by afalhambra** [Hyperfoil/Hyperfoil#236]
Would be nice to provide any option to format the [timestamp step](https://hyperfoil.io/docs/steps/step_timestamp.html) available in hyperfoil. Currently this timestamp step is only provided as the `System.currentTimeMillis()` but this is a limitation for some use cases where the current timestamp is needed but in a different date format.

For instance, in our particular case, we are using [standard cloud events](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#time) where one of the optional attributes is `time` with a [particular date format](https://tools.ietf.org/html/rfc3339). For example, see `time` field format:

```
{
    "specversion" : "1.0",
    "type" : "com.github.pull_request.opened",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "id" : "A234-1234-1234",
    "time" : "2022-08-03T17:57:20.426362Z",
    "data" : "abc"
}
```

**Comment by rvansa** [comment]
Done in f953d35a4e8de2e89e2125753f585d50f2ed008c
