### ISSUE TITLE
startWith with delay

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#239]
For simulation spikey loads it might be useful to execute steady state and then add additional load in parallel. This could be defined through a combination of phase name and delay like
```
startWith:
  phase: anotherPhase
  delay: 120s
```
Combining that with other `startAfter`/`startAfterStrict` constraints or `startTime` should be illegal; we want these phases in sync.

**Comment by lampajr** [comment]
Hey @jesperpedersen , is this still a valid issue? if so, may I try to take it?

**Comment by jesperpedersen** [comment]
Sync with @franz1981 on it

**Comment by lampajr** [comment]
great, thanks a lot @jesperpedersen !
