### ISSUE TITLE
Verify functionality of openshift routing

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#26]
We need to verify that if we create new connections to a load balanced application in OpenShift that if we send multiple requests, and ramp up connections/requests, that the requests are routed through the router and not directly to the pod.  We need to ensure that as the load increases, requests made over existing connections are sent to the router and not directly to the pods

**Comment by rvansa** [comment]
So I ran a quick test in the lab and HF's connection pooling behaves the worst way possible. With single connection open, it always hits the same node, even though I scale replicas. With two connections, it doesn't load-balance either, just picks a free connection.

**Comment by rvansa** [comment]
The code was buggy; In fact it loadbalances targets even with single connection. This is what I was hoping for when I read that the router keeps one connection pointing in and another out (therefore you have to set max connections on router to two-times # of expected connections). And the load balancing is executed per request, not only when the connection is initiated.

Btw., that also means that we could keep the same connection pool to multiple hosts withing OCP as long as these resolve to the same IP. That's another story, though.

Marking this as resolved as we don't need any further work in Hyperfoil.
