### ISSUE TITLE
Wrk/Wrk2 commands do not test remote URL before starting benchmark

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#265]
The `wrk` or `wrk2` commands do not test the remote connection before starting the benchmark and these commands fail with a unclear error message;

```
Running 10s test @ http://localhost:8080/hello
  2 threads and 10 connections
java.lang.IllegalStateException: Missing stats for phase 'test'
```

these command should fail fast with the following error;

```
unable to connect to localhost:8080 Connection refused
```

**Comment by johnaohara** [comment]
This can be caused if there is no remote service listening on a port, or the service is returning a response that is not valid, e.g. 

```
#1 Sequence request(0)(4/4), request (#1, RUNNING, INVALID) GET localhost:8080/hello on connection Http1xConnection{/127.0.0.1:56617 -> localhost/127.0.0.1:8080, status=OPEN, size=1+0:[(#1, RUNNING, INVALID) GET localhost:8080/hello]} received invalid status 406
```

The endpoint needs to be validated before the bechmark load is run, with an appropriate error message displayed

**Comment by lampajr** [comment]
This was fixed by https://github.com/Hyperfoil/Hyperfoil/pull/266, can close this as completed.

@johnaohara feel free to re-open if I misunderstood.
