### ISSUE TITLE
Does event bus guarantee ordering of events on event bus?

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#27]
Do we need to attach a sequenceID to 1s histograms that are sent across event-bus from agents to controller, so that we aggregate histogram data in the correct order?  Does the event bus guarantee order? if not, can we configure vert.x event bus to guarantee ordering?

**Comment by rvansa** [comment]
It seems that eventbus should persist the order of messages from the same sender to the same receiver.

However this is irrelevant in the end; It seemed better to send delta-histograms as these are gathered, so the sequence ids are necessary.
