### ISSUE TITLE
PR #266 adds 2 runs per execution of wrk/wrk2

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#272]
This PR: https://github.com/Hyperfoil/Hyperfoil/pull/266

caused a side effect where the validate phase of the `wrk`/`wrk2` commands create a new invalid run that is visible in the `runs` command. 

```
   RUN_ID  BENCHMARK  STARTED                  TERMINATED               DESCRIPTION
?  001A    wrk                                 2023/01/27 10:39:11.115             
!  001B    wrk        2023/01/27 10:39:13.053  2023/01/27 10:39:29.059             
?  001C    wrk2                                2023/01/27 10:39:49.177             
+  001D    wrk2       2023/01/27 10:39:57.415  2023/01/27 10:40:13.420
```

Runs `001A` and `001C` are not actual runs

**Comment by lampajr** [comment]
With this https://github.com/Hyperfoil/Hyperfoil/pull/400 this should be fixed:
- No more additional run is displayed (and actually executed)
- The wrk/wrk2 still returns user-friendly error message if something foes wrong during initialization (e.g., endpoint unreachable)
