### ISSUE TITLE
Update to JDK LTS version 11 (and 9).

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Hyperfoil#29]
As of today we have JDK12 at GA state and JDK13 only round the corner.

 This project needs to keep up with the frequent release cycles to remain fresh.

**Comment by rvansa** [comment]
It seems our dear Sanne already handled that https://github.com/kohsuke/metainf-services/commit/ef5c9c858ee23f54e7697c95657bd64a898e50d6 so I just had to bump version.
