### ISSUE TITLE
arrow keys navigation not working on web-cli

### ISSUE THREAD

**Issue by rafaeltuelho** [Hyperfoil/Hyperfoil#290]
If you try to use narrow keys (Up/Down key to be more specific) to navigate through commands in the web-cli it messes up the console with html code/characters.

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/39063/234626059-d5260400-0dc3-4c78-a691-825c09beb891.png">

Also the embedded text editor stops working after a while. You have to close (losing your changes) it and reopen it.

Hyperfoil CLI, version 0.23
Tested on MacOS 12.6.5
Firefox 102.9.0
Chrome 112.0.5615.49 (Official Build) (x86_64)

**Comment by jesperpedersen** [comment]
@franz1981 @stalep
