### ISSUE TITLE
the embedded text editor stops working after a while

### ISSUE THREAD

**Issue by rafaeltuelho** [Hyperfoil/Hyperfoil#292]
When editing a benchmark definition using the web-cli embedded text editor, it stops working as if it did not receive commands from the keyboard. You have to close (losing your changes) it and reopen it.

My env:

```
Openshift 4.12.12
Hyperfoil CLI, version 0.23
Tested on MacOS 12.6.5
Firefox 102.9.0
Chrome 112.0.5615.49 (Official Build) (x86_64)
```

**Comment by johnaohara** [comment]
@rafaeltuelho  I am struggling to re-create this issue. all of the edits remain in the browser until the changes are saved, so this must be related to something with the editor.

How large is the benchmark definition?  
Does this issue occur immediately, or only after making a few changes? 
Could it be related to the time spent editing/the number of edits made to the benchmark definition?

**Comment by rafaeltuelho** [comment]
It happens after trying a few changes like copying/pasting, and moving lines. I noticed when it stop working and you close it, the changes get written to the terminal command line. Weird.

**Comment by johnaohara** [comment]
@rafaeltuelho I have not been able to re-create this issue on Linux or Mac.  However, there is no network traffic between the browser and controller during edits, only when the benchmark definition is loaded or saved. 

I have bumped the monaco-editor to the latest release (0.22.3 was over 2 years old).  Hopefully this will resolve the issue of the editor becoming unresponsive
