### ISSUE TITLE
Missing release 0.25 on quay.io

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Hyperfoil#307]
Hello team,

I just noticed that the last release `0.25` is not present on quay.io [1], the latest one is stil `0.24.2`.
Is that expected?

[1] https://quay.io/repository/hyperfoil/hyperfoil?tab=tags

**Comment by jesperpedersen** [comment]
0.25.0 apparently wasn't uploaded - 0.25.1 is on the site now

**Comment by lampajr** [comment]
Thanks a lot @jesperpedersen !

**Comment by jesperpedersen** [comment]
@lampajr 0.25.2 is up with your fix
