### ISSUE TITLE
Running Hyperfoil HotRod with remote agents sometimes gets stuck in READY state

### ISSUE THREAD

**Issue by wburns** [Hyperfoil/Hyperfoil#333]
When running Hyperfoil controller and 2 agents on different machines many times it never starts despite running the first phase.

![image](https://github.com/Hyperfoil/Hyperfoil/assets/648175/49233224-bf25-48c4-9903-1929c2f32ea3)
 
Here is an image of when it happens. I am forced to kill the run and retry again. It happens around half the time.

The image is running the benchmark and it showing READY but never showing the phase durations left and then switching to stats seeing it is actually running and finally back to status which is still stuck.

**Comment by franz1981** [comment]
The same benchmark (without controller) works correctly locally?
can you share the benchmark definition?

**Comment by wburns** [comment]
It is not the same as #323 as I have seen that once, which kills the run completely.

I can very easily reproduce this with my EC2 benchmark, over half of the time recently :(

The benchmark definition is https://github.com/infinispan/infinispan-ansible-benchmark/blob/main/benchmarks/hotrod-benchmark.yaml.j2. You can ignore the agents part at the top, that is just so ansible can populate it for me automatically.

**Comment by franz1981** [comment]
> over half of the time recently :

which seems to suggest to a timing issue: the benchmark definition seems one of the quickstarts, meaning it should't be problematic.

Do you have any logs from agent/controllers? To understand if something suspicious is happening?
Same for heap dump (stack trace won't be probably very useful there...), so I can inspect in which states agent/controller(s) believe to be.

> I have not tried with an agent, if that is what you meant by locally.

Yep, and (IDK if is possible), with a local setup too (single agent), to understand if can be reproduced locally, too.

**Comment by wburns** [comment]
Yeah, I was going to try to dig into it further today when I get some time. I can get the logs of both and attach as well.

**Comment by wburns** [comment]
[hfc-ip-172-31-12-151.log](https://github.com/Hyperfoil/Hyperfoil/files/14828545/hfc-ip-172-31-12-151.log)

Attached is a log file. If you notice runs 0000-0002 all ran fine. But then 0003 didn't, the rampup phases never received a status update. So it sounds like the agents aren't sending the messages back in some cases.

Looking at the agent log it seems to just forever do the rampupGet and rampupPut phases and always prints "no progress, not finished." So it looks like a bug in the agent code somehow

[agent.ec2-3-149-27-128.us-east-2.compute.amazonaws.com.log](https://github.com/Hyperfoil/Hyperfoil/files/14828614/agent.ec2-3-149-27-128.us-east-2.compute.amazonaws.com.log)

**Comment by wburns** [comment]
Another set of logs from a run, this time it failed on 0000 and the GUI never showed any status update, constantly saying the agents were only READY despite stats updating.

[agent.ec2-18-217-180-82.us-east-2.compute.amazonaws.com.log](https://github.com/Hyperfoil/Hyperfoil/files/14829458/agent.ec2-18-217-180-82.us-east-2.compute.amazonaws.com.log)
[hfc-ip-172-31-15-102.log](https://github.com/Hyperfoil/Hyperfoil/files/14829459/hfc-ip-172-31-15-102.log)

**Comment by wburns** [comment]
Thread dump does not show anything interesting, however #334 seems to remedy the issue. It seems to be some sort of issue that if the HotRod RemoteCacheManager is started on the same event loop that is currently starting it it gets Hyperfoil into an invalid state and it never transitions into the next phase. With the changes I have never experienced the issue, however without it I can run into the issue over 50% of the time easily.
