### ISSUE TITLE
Propagate termination error back to cli

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#34]
If an error occurs running the benchmark from the cli, propagate the exception back to the cli so users know the reason for benchmark failure. atm, users need to check process output to determine the cause of error

**Comment by rvansa** [comment]
Done - I've improved the `status` and `run-local` commands a bit. Any code that wishes to fail the phase must call `Session.fail(Throwable)` - the exception message, it's causes and originating agent will end up in the console.

**Comment by johnaohara** [comment]
Thanks
