### ISSUE TITLE
On `wrk` the session allocates `maxRequests`-size HttpRequestPool

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Hyperfoil#380]
On `wrk` the session allocates by default `maxRequests`-size (16) HttpRequestPool even if the default behavior on the original `wrk` is to use 1 single request concurrency per connection.

This could be related to the pipelining (see https://github.com/Hyperfoil/Hyperfoil/issues/277).

**Comment by lampajr** [comment]
Looking at this problem we noticed that we are currently storing the HttpRequestPool on every session https://github.com/Hyperfoil/Hyperfoil/blob/80c2bfc2f483ee2baf53ea26cbbe830305310462/http/src/main/java/io/hyperfoil/http/HttpRunData.java#L116

This could end up in huge allocation when using an high rates.

**Comment by lampajr** [comment]
Generally the `maxRequests` should be set to the `pipelining limit` * `shared connections`.

**Comment by franz1981** [comment]
This is for reference a screenshot of a run with wrk2 with rate 100K rps, using 10 connections:
![image](https://github.com/Hyperfoil/Hyperfoil/assets/13125299/228dfcfe-f1db-41c6-97e4-3fa53c738c60)

**Comment by franz1981** [comment]
FYI @lampajr just setting it == number of connections on WrkAbstract at  https://github.com/Hyperfoil/Hyperfoil/blob/80c2bfc2f483ee2baf53ea26cbbe830305310462/cli/src/main/java/io/hyperfoil/cli/commands/WrkAbstract.java#L330 on the scenario (we have 2 for wrk actually...)

we have

![image](https://github.com/Hyperfoil/Hyperfoil/assets/13125299/ded1bc6b-95da-4390-9362-fad156d7d367)

which is way better but still. IDK how these are populated; they just look to be way too much to me TBH.
I need to debug and see what happen to understand how we create them...

**Comment by franz1981** [comment]
Using the modified version using 10 maxrequests I see something interesting:
![image](https://github.com/Hyperfoil/Hyperfoil/assets/13125299/440abc3a-4c25-47c0-8edc-52876e093477)

we have 4 scenarios created, and still...

**Comment by franz1981** [comment]
And indeed I see that each sessions got its own configured HttpRequestPool with its own HttpRequest (not shared)!

**Comment by franz1981** [comment]
it seems that https://github.com/Hyperfoil/Hyperfoil/blob/80c2bfc2f483ee2baf53ea26cbbe830305310462/http/src/main/java/io/hyperfoil/http/HttpRunData.java#L116 is just creating a new pool for each `Session` while the http request (and pool) should belong to each connection created, instead.

**Comment by franz1981** [comment]
A much better solution here should be to have a single HttpRequestPool shared among different sessions, which have a capacity automatically set to never exceed the "natural concurrency" of the given protocol i.e. Http 1.1 is max connection * pipelining while HTTP 2 is max connection * max streams.

**Comment by franz1981** [comment]
I've added an additional commit doing something similar for `SequenceInstance` and getting

![image](https://github.com/Hyperfoil/Hyperfoil/assets/13125299/8c0c3155-ef0a-4904-b173-558e0c92e229)

![image](https://github.com/Hyperfoil/Hyperfoil/assets/13125299/1e48a9fa-370f-418a-bb48-ce7455522e96)

**Comment by franz1981** [comment]
Closed via #382
