### ISSUE TITLE
Non-constant string concatenation as argument to 'error()' logging call 

### ISSUE THREAD

**Issue by lampajr** [Hyperfoil/Hyperfoil#407]
There are some places where the log message is not properly computed, e.g.,

```java
log.error("Cannot start " + name, e);
```
And the concatenation is calculated beforehand the condition check. So if that logging message is in the hot path and gets called many times, e.g., 10K times but the condition check is always false, you will be concatenating 10K times with no reason.

Therefore, it should be refactored as:
```java
log.error("Cannot start {}", name, e);
```

**Comment by mini0192** [comment]
Can i work this issue?

**Comment by franz1981** [comment]
yes @mini0192 you have my vote
Let me add a nice label here, to help

**Comment by lampajr** [comment]
>Can i work this issue?

@mini0192 sounds great, I assigned this issue to you!
Do not hesitate to ask any question or doubt :rocket: 

>uh @lampajr already has done it, great (the label!)

hehe :smile:

**Comment by lampajr** [comment]
Just to give a bit more context, the example provided in the issue description is just one single occurrence but for sure there are other as well that should be fixed (including other logging levels)
