### ISSUE TITLE
Merge ValidatorResults into StatisticsSnapshot

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#5]

**Comment by whitingjr** [comment]
Could try implementing The Pairwise algorithm documented in this [doc](i.stanford.edu/pub/cstr/reports/cs/tr/79/773/CS-TR-79-773.pdf).
An example in Java is [here](https://github.com/akara/faban/blob/master/driver/src/com/sun/faban/driver/util/PairwiseAggregator.java).

**Comment by rvansa** [comment]
@whitingjr This issue rather talks about refactoring classes; ValidatorResults is a separate class that keeps derived info about statuses; we should move those fields into StatisticsSnapshot.

**Comment by rvansa** [comment]
Done.
