### ISSUE TITLE
Export statistics

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#55]
I would be really nice to have a command to export statistics to a file. It would really help when running hyperfoil in automated scripts, so we can store the results without parsing console output or searching in /tmp/hyperfoil dir.

**Comment by rvansa** [comment]
@mocenas You mean when running using `run-local` in CLI? I admit that mode of operation is rather neglected; usually we start server and that dumps all statistics both to bunch of CSV files and JSON file after the run is complete.

**Comment by mocenas** [comment]
@rvansa It would be nice to have it using `run-local`, I can find use for it too. By those CSV and JSON, you mean those in `/tmp/hyperfoil/run/X/stats` or something other?

**Comment by rvansa** [comment]
@mocenas Ok, I can add it.

Yes, there are CSVs in `stats` and one big JSON `all.json` that describes the run completly (except hooks output, but hooks are not documented yet anyway).

**Comment by mocenas** [comment]
After running a few runs client - standaloneServer, I found no JSON files at all in` /tmp/hyperfoil.`  Also digging up the right CSV files this way, is really not comfortable. 
Thanks in advance if there will be way to access results in easier way.

**Comment by rvansa** [comment]
Hi @mocenas could you check out b3cc902cfe10a18ab949104eff15e9b1ff593fc8 ? I've deprecated the `run-local` command, replacing it with `start-local` which starts the controller in-vm and automatically connect you to it. The rest is identical as if you connected to already running controller, you `upload` the benchmark, `run` it and check `stats`. The controller stores the results in `/tmp/hyperfoil/run/XXXX/`.

**Comment by rvansa** [comment]
TODO: CLI command `export` to download results to local machine.

**Comment by rvansa** [comment]
Done in afa7de22f5e207507464bbcb1d08fecf25c3f407
