### ISSUE TITLE
Warn if InetAddress.getLocalHost() returns localhost

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#57]
When `InetAddress.getLocalHost()` returns localhost/127.0.0.1 clustering won't work. Make sure to print that to the log with big red letters.

**Comment by rvansa** [comment]
Implemented in fc1f2475e0bce8c5ff8fb7529d7466e0a07ab6be

**Comment by whitingjr** [comment]
When I tested the fix I am seeing the controller still fail to use the cluster address.

> 15:20:11,109 INFO  (main) [i.h.H.Controller] Starting Vert.x...
> 15:20:11,211 INFO  (main) [i.h.H.Controller] Using host name injector-controller/192.168.42.45
> 15:20:13,801 INFO  (main) [i.h.HyperfoilChannelLookup] Reducing join timeout.
> 15:20:13,801 INFO  (main) [i.h.HyperfoilChannelLookup] Using 127.0.0.1:7800 as clustering address
> 15:20:13,843 INFO  (main) [o.j.p.p.GMS] injector-controller-6278: no members discovered after 7 ms: creating cluster as first member
> 15:20:17,625 INFO  (vert.x-eventloop-thread-0) [i.h.H.Controller] Deploying ControllerVerticle...
> 15:20:17,646 INFO  (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Starting in directory /tmp/hyperfoil/workspace...
> 15:20:17,892 INFO  (vert.x-eventloop-thread-1) [o.a.s.c.u.s.e.EdDSASecurityProviderRegistrar] getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
> 15:20:18,046 INFO  (vert.x-eventloop-thread-1) [o.a.s.c.i.DefaultIoServiceFactoryFactory] No detected/configured IoServiceFactoryFactory using Nio2ServiceFactoryFactory
> 15:20:18,079 INFO  (vert.x-eventloop-thread-0) [i.h.H.Controller] ControllerVerticle deployed.
> 15:20:21,654 INFO  (vert.x-worker-thread-7) [i.h.c.u.PersistenceUtil] Stored benchmark '3scale-benchmark' in /tmp/hyperfoil/workspace/benchmark/3scale-benchmark.serialized
> 15:20:21,655 INFO  (vert.x-worker-thread-7) [i.h.c.u.PersistenceUtil] Stored benchmark '3scale-benchmark' in /tmp/hyperfoil/workspace/benchmark/3scale-benchmark.yaml
> 15:20:22,157 INFO  (vert.x-eventloop-thread-1) [i.h.c.u.PersistenceUtil] Stored benchmark '3scale-benchmark' in /tmp/hyperfoil/workspace/run/0000/3scale-benchmark.serialized
> 15:20:22,157 INFO  (vert.x-eventloop-thread-1) [i.h.c.u.PersistenceUtil] Stored benchmark '3scale-benchmark' in /tmp/hyperfoil/workspace/run/0000/3scale-benchmark.yaml
> 15:20:22,158 INFO  (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Starting agents for run 0000
> 15:20:22,194 INFO  (vert.x-worker-thread-8) [o.a.s.c.c.h.DefaultConfigFileHostEntryResolver] resolveEffectiveResolver(vagrant@192.168.42.46:22) loaded 1 entries from /home/vagrant/.ssh/config
> 15:20:52,163 ERROR (vert.x-eventloop-thread-1) [i.h.c.ControllerVerticle] Deployment timed out.
> 15:20:52,163 INFO  (vert.x-eventloop-thread-1) [i.h.d.s.SshDeployedAgent] Stopping agent 192.168.42.46
 When getting the [JGroups channel](https://github.com/Hyperfoil/Hyperfoil/blob/master/clustering/src/main/java/io/hyperfoil/HyperfoilChannelLookup.java#L23) the manually configured IP is [overwritten](https://github.com/Hyperfoil/Hyperfoil/blob/master/clustering/src/main/java/io/hyperfoil/HyperfoilChannelLookup.java#L38). With the address JGroups considers to be the bind address. 
 You can see from the above log the address 127.0.0.1 is returned by JGroups. Surely the channel should be using the manually configured controller cluster IP ?

**Comment by rvansa** [comment]
So the problem is in ansible scripts; these manually set `jgroups.tcp.address` to `ansible_hostname` and then the code inside Hyperfoil is ignored.

**Comment by rvansa** [comment]
Aah, and I did one silly mistake...

**Comment by rvansa** [comment]
... and Vert.x was binding to wrong address, too.

**Comment by rvansa** [comment]
... but agents don't know how to pick their clustering addresses...

**Comment by whitingjr** [comment]
exactly. Should a property be passed to the Agent when it's being deployed to instruct which address to override and connect to the cluster with ?

**Comment by rvansa** [comment]
In the end I've decided to solve such case by iterating through all IP addresses and finding one that has longest common prefix with the controller IP.
Passing the bind address would complicate Deployer which doesn't know much of the node.
