### ISSUE TITLE
Openshift controller fails to load benchmark

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#64]
I tried installing and running openshift controller following the manual [here](https://hyperfoil.github.io/docs/installation.html#deploying-in-kubernetesopenshift).
Controller was deployed without a problem and CLI connected to it. But when I tried to upload a benchmark (using k8s-hello-world.hf.yaml from the manual) and ended up with error:

`
[hyperfoil@hyperfoil-hyperfoil]$ upload example.yml
Loaded benchmark k8s-hello-world, uploading...
ERROR: io.hyperfoil.client.RestClientException: Server responded with unexpected code: 400, Bad Request: Server responded with unexpected code: 400, Bad Request
Failed to upload the benchmark.
`
Pod has exception in log:
`
10:17:36,520 ERROR (vert.x-eventloop-thread-1) [i.h.c.ControllerServer] Failed to serialize java.io.InvalidClassException: io.hyperfoil.api.config.Benchmark; local class incompatible: stream classdesc serialVersionUID = -32778862036102936, local class serialVersionUID = 2815029909819311504
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1884)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1750)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2041)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at io.hyperfoil.util.Util.deserialize(Util.java:82)
`

The example from manual should work.

Also CLI may display some more useful error message than just "Bad request".

**Comment by rvansa** [comment]
Good point, I'll improve the message. You had different version of CLI and controller, didn't you? You can check client & server version in CLI using the `version` command.

**Comment by mocenas** [comment]
Yea I downloaded a new version of hyperfoil and works fine now. Sorry for false alarm.

**Comment by rvansa** [comment]
I'll also add a warning about mismatching versions right to the `connect` command.

**Comment by mocenas** [comment]
That would be good.

**Comment by rvansa** [comment]
Done  in f95d8886e9617a52d63a4ab1b07092149a27328e and b89dbb42dc9f33a89e4c85edd503d96bfdb3f1f2
