### ISSUE TITLE
CLI gets stucked after CTRL+D in while connected

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#65]
version: hyperfoil-0.5

CLI can be ended by writing `exit; quit` or pressing CTRL+D (on Linux - end of file). All of this works fine just after starting CLI.
Once I connect to the server, exit and quit still works fine, but pressing CTRL+D causes CLI to stuck. While stucked CLI does not react to anything and I had to `kill -9` it to close it.

**Comment by rvansa** [comment]
Never used Ctrl+D. @stalep Can you hook EOF to a command in Aesh?

**Comment by stalep** [comment]
Æsh-readline has handler support when the connection is closed (which a Ctrl-D on an empty line is).
github/aeshell/aesh#315

**Comment by stalep** [comment]
Implemented a fix for this now. @rvansa I'm planning a new version of Æsh early next week, the fix will be there. Settings.setConnectionHandler(Consumer<Void>) is the method to use. That will be called when the connection closes.

**Comment by rvansa** [comment]
Handled in 15718c7c8bb3e5c6227603d8d26c90e8bfd3823f and finally fixed through bd949e3b490a8dc4a238331e3a836e2b73dc9266.
