### ISSUE TITLE
Unable to upload to openshift controller

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#83]
Following the instructions on https://hyperfoil.github.io/docs/k8s_manual.html I created a controller, downloaded up to date hyperfoil and tried to connect to it. Connection OK but when uploading the benchmark, I received error message:

```
[hyperfoil@hyperfoil-hyperfoil]$ upload scenario.yml
Loaded benchmark random-urls, uploading...
ERROR: Server responded with unexpected code: 400, Bad Request:
Cannot read benchmark - the controller (server) version and CLI version are probably not in sync.
This partial stack-track might help you diagnose the problematic part:
---
java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1884)
java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1750)
java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2041)
java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1572)
java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
io.hyperfoil.util.Util.deserialize(Util.java:88)
---

Failed to upload the benchmark.
```

Both the CLI and controller are new - just downloaded.

Attaching also controller log
[log.log](https://github.com/Hyperfoil/Hyperfoil/files/4025546/log.log)

Also the CLI every few seconds writes a message:
`Warning: controller seems offline.`

**Comment by mocenas** [comment]
If CLI can detect that versions are not in sync, can it also print both of them? It would help investigating such errors.

**Comment by rvansa** [comment]
@mocenas There's a `version` command that prints both.

**Comment by mocenas** [comment]
Thanks, tried command version and result seems not right:
```
Server: unknown
Client: 0.5, 039fc2a4eeb2387fdea7aec1c71f3da60ce17db2
```

**Comment by rvansa** [comment]
The download link on website was not updated to `0.6`, fixed.
