### ISSUE TITLE
Feature request: export - force override

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#84]
Please add an option to force override file during export.
Now if file doesn't exist, it just creates an output file, if it does exist it ask if it should override it. It would be nice to have consistent behaviour. Especially if used in scripting.

**Comment by rvansa** [comment]
Implemented. I must add some option to print curl queries so that people stop using CLI for scripts (that's why there's REST API!).

**Comment by mocenas** [comment]
@rvansa that curl queries would be good. But it would be even better to have documentation to the API.

**Comment by rvansa** [comment]
The REST API is documented: https://github.com/Hyperfoil/Hyperfoil/blob/master/controller-api/src/main/resources/openapi.yaml
