### ISSUE TITLE
REST API - parseable runId

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#85]
I have some ideas how to improve controller REST API.
When starting a benchmark, using `/benchmark/<benchmarkName>/start` It returns string:
`Starting benchmark random-urls, run ID 0001`
Please place the run ID in some easy parseable format. At least on single line like:
`runId: 0000` So it can be parsed by something like | grep | cut.

**Comment by rvansa** [comment]
You could have already parsed the `Location` header returned by that command.
Anyway, I've changed the return value to use JSON.
