### ISSUE TITLE
No error if openshift agents fails to start

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#92]
When openshift controller fails to start some agents (we have an issue with openshift - so some agent doesn't started). After some time, controller will terminate the agents and the run. But no error is reported. Report in that case looks like:
```
{
  "info": {
    "id": "0007",
    "benchmark": "random-urls",
    "startTime": -9223372036854775808,
    "terminateTime": 1578921798847,
    "cancelled": false,
    "description": null,
    "errors": []
  },
  "total": [],
  "failure": [],
  "agent": {}
}
```
So no errors, no failures not cancelled. Some of these should be set.

**Comment by rvansa** [comment]
Fixed.
