### ISSUE TITLE
Reflective access calls causing WARNING messages for jre >8.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Hyperfoil#93]
When the controller jvm start I am seeing this warning message.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.marshalling.reflect.JDKSpecific$SerMethods (file:/home/benchuser/jwhiting/3scale/hyperfoil-0.6-SNAPSHOT/lib/jboss-marshalling-osgi-2.0.6.Final.jar) to constructor java.util.AbstractMap()
WARNING: Please consider reporting this to the maintainers of org.jboss.marshalling.reflect.JDKSpecific$SerMethods
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

 The cause is a transitive dependency called jboss-marshalling-osgi. This dependency excludes the Multi Release jar implementations of JDKSpecific$SerMethods. The default implementation uses reflection.

**Comment by rvansa** [comment]
Fixed in #94
