### ISSUE TITLE
Reconsider all.json structure?

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#95]
@willr3 I am trying to document all.json structure in a schema and I wonder why you decided to single-out `total` from the data. To me, it would make more sense to put the summary on the same level as `histogram`.

**Comment by rvansa** [comment]
@willr3 Did we discuss this in the end?

**Comment by willr3** [comment]
the current all.json schema was based on the file structure from the csv's and how the data is collected in HF. I don't have a sample in front of me, can you elaborate what structure you think should be changed?

**Comment by rvansa** [comment]
OK, if you were strictly following CSVs (where we single out totals for easy viewing) I understand the structure.

I was talking about having paths like `total[].summary` (hosting stats snapshot) and `phase.phaseName.iteration.iterationId.fork.forkName.metric.metricName.(series[], histogram,...)` (`series[]` is also stats snapshot). My original question was about putting `total` on the same level as `series[]`.
Looking at it now, I wonder if those `iteration`, `fork`, `metric` have any meaning since the object with that field has always a single field (the name). I would flatten it by removing these, or maybe even flatten it all the way so that you'd have:
```json
{
  "failures": [ ... ]
  "stats": [
    {
       "phase": "my-phase",
       "iteration": "xxx",
       "fork": "my-fork",
       "metric": "my-metric",
       "total": { <snapshot> },
       "series": [ { <snapshot1> }, { <snapshot2>, ... } ]
       "histogram": {
         "percentiles": [ ... ],
         "linear": [ ... ]
       }
    }
  ]
}
```

**Comment by rvansa** [comment]
Integrated as `http://hyperfoil.io/run-schema/v2.0`
